name: hockeysticks
favicon: null
layout_spectrum: 0.4652560125105083
typography_spectrum: 0.7105556051246822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1781152281910181
  lightness: 0.34905709559097886
  saturation: 0.3267483070958406
  rhythmicContrast: 0.15422603930346668
purpose: []
